Repository gnosis/cowswap, pull requests merged in 2021-12, with the labels that each got.

#1900 Merge /profile and /trades api queries in order to get trades
  src/custom/utils/trade.ts
Labels: 🐞 Bug, Protofire

#1952 RC 1.6.0
  .github/stale.yml
  README.md
  package.json
  public/index.html
  src/components/AccountDetails/index.tsx
  src/custom/abis/types/index.ts
  src/custom/api/gnosisProtocol/api.ts
  src/custom/api/gnosisProtocol/hooks.ts
  src/custom/components/AccountDetails/index.tsx
  src/custom/components/AccountDetails/styled.ts
  src/custom/components/CurrencyInputPanel/FiatValue/FiatValueMod.tsx
  src/custom/components/NotificationBanner/index.tsx
  src/custom/components/SearchModal/CurrencyList/CurrencyListMod.tsx
  src/custom/components/SearchModal/CurrencyList/index.tsx
  src/custom/components/SearchModal/ImportRow/ImportRowMod.tsx
  src/custom/constants/index.ts
  src/custom/hooks/useContract.ts
  src/custom/hooks/useFilterEmptyQueryParams.ts
  src/custom/hooks/useRecentActivity.ts
  src/custom/hooks/useTokenLazy.ts
  src/custom/pages/App/index.tsx
  src/custom/pages/Faq/index.tsx
  src/custom/pages/Swap/SwapMod.tsx
  src/custom/pages/TermsAndConditions/TermsAndConditions.md
  src/custom/state/affiliate/hooks.ts
  src/custom/state/affiliate/updater.tsx
  src/custom/state/enhancedTransactions/actions.ts
  src/custom/state/enhancedTransactions/reducer.ts
  src/custom/state/enhancedTransactions/updater/CancelReplaceTxUpdater.tsx
  src/custom/state/orders/actions.ts
  src/custom/state/orders/consts.ts
  src/custom/state/orders/hooks.ts
  src/custom/state/orders/reducer.ts
  src/custom/state/orders/updaters/ApiOrdersUpdater.ts
  src/custom/state/orders/updaters/CancelledOrdersUpdater.ts
  src/custom/state/orders/updaters/PendingOrdersUpdater.ts
  src/custom/state/orders/updaters/UnfillableOrdersUpdater.ts
  src/custom/state/orders/updaters/index.ts
  src/custom/state/orders/updaters/utils.ts
  src/custom/state/orders/utils.ts
  src/custom/utils/explorer.ts
  src/hooks/Tokens.ts
  src/index.tsx
  src/state/multicall/hooks.ts
  src/state/multicall/updater.tsx
  src/theme/components.tsx
  yarn.lock
Labels: 🚀 RELEASE

#1966 FAQ: Fixed some typos and did minor phrasing edits.
  src/custom/pages/Faq/index.tsx
Labels: Auto-merge

#1967 Bump dex-js to 0.13.0 to fix issue with trailing dot
  package.json
  yarn.lock
Labels: Auto-merge

#1968 [CLEANUP] useUSDCPrice speedup + logs clean
  .mergify.yml
  package.json
  src/custom/hooks/useUSDCPrice/index.ts
  src/custom/pages/Swap/SwapMod.tsx
Labels: 🚀 RELEASE

#1985 [ABA impact] Show eager loader
  src/custom/hooks/usePriceImpact/index.ts
  src/custom/hooks/usePriceImpact/types.ts
  src/custom/hooks/usePriceImpact/useFallbackPriceImpact.ts
  src/custom/hooks/usePriceImpact/useFiatValuePriceImpact.ts
  src/custom/hooks/usePriceImpact/useQuoteAndSwap.ts
Labels: 🚀 RELEASE

#1986 [ABA impact] - Re-enable Fiat Price Impact + minor optimisations
  src/custom/components/SwapWarnings/index.tsx
  src/custom/hooks/usePriceImpact/index.ts
  src/custom/hooks/usePriceImpact/types.ts
  src/custom/hooks/usePriceImpact/useFallbackPriceImpact.ts
  src/custom/hooks/usePriceImpact/useQuoteAndSwap.ts
  src/custom/pages/Swap/SwapMod.tsx
Labels: 🚀 RELEASE

#1935 [Profile] Add explorer orders link to Profile page and app menu
  src/custom/api/gnosisProtocol/hooks.ts
  src/custom/components/Menu/index.tsx
  src/custom/pages/Profile/index.tsx
  src/custom/pages/Profile/styled.tsx
Labels: Protofire

#2000 Basic claim
  src/components/Menu/index.tsx
  src/custom/components/Header/HeaderMod.tsx
  src/custom/components/Header/index.tsx
  src/custom/components/Menu/MenuMod.tsx
  src/custom/components/Menu/index.tsx
  src/custom/pages/App/AppMod.tsx
  src/custom/pages/App/index.tsx
  src/custom/pages/Claim/index.tsx
  src/custom/state/claim/hooks/hooksMod.ts
  src/custom/state/claim/hooks/index.ts
  src/custom/state/enhancedTransactions/actions.ts
  src/custom/state/enhancedTransactions/reducer.ts
Labels: Auto-merge

#2018 Hotfix 1.7.3 - Winter has come
  package.json
  public/audio/archive/mooooo-error__ORIGINAL.mp3
  public/audio/archive/mooooo-halloween.wav
  public/audio/archive/mooooo-halloween__lower.wav
  public/audio/archive/mooooo-send__ORIGINAL.mp3
  public/audio/archive/mooooo-success__ben__ORIGINAL.mp3
  public/audio/archive/mooooo-success__old.mp3
  public/audio/mooooo-error__lower-30.mp3
  public/audio/mooooo-error__lower-50.mp3
  public/audio/mooooo-send__lower-30.mp3
  public/audio/mooooo-send__lower-50.mp3
  public/audio/mooooo-send__lower-80.mp3
  public/audio/mooooo-send__winter-edition.mp3
  public/audio/mooooo-success__ben.m4a
  public/audio/mooooo-success__ben__lower-30.mp3
  public/audio/mooooo-success__ben__lower-50.mp3
  src/custom/assets/cow-swap/santa.png
  src/custom/components/Header/index.tsx
  src/custom/state/orders/middleware.ts
  yarn.lock
Labels: 🚀 RELEASE

#2017 [Release 1.8] Use new quote endpoint for USD estimations
  src/custom/hooks/useDebounceWithForceUpdate.ts
  src/custom/hooks/usePriceImpact/useFallbackPriceImpact.ts
  src/custom/hooks/usePriceImpact/useQuoteAndSwap.ts
  src/custom/hooks/useRefetchPriceCallback.tsx
  src/custom/hooks/useSwapCallback.ts
  src/custom/hooks/useUSDCPrice/index.ts
  src/custom/state/price/updater.ts
  src/custom/utils/price.ts
Labels: 🚀 RELEASE

#2016 [Release 1.8] Use real price strategy endpoint
  src/custom/api/gnosisProtocol/api.ts
  src/custom/constants/index.ts
  src/custom/hooks/useDebounceWithForceUpdate.ts
  src/custom/hooks/useGetGpPriceStrategy.ts
  src/custom/hooks/usePriceImpact/useFallbackPriceImpact.ts
  src/custom/hooks/usePriceImpact/useQuoteAndSwap.ts
  src/custom/hooks/useRefetchPriceCallback.tsx
  src/custom/hooks/useSwapCallback.ts
  src/custom/hooks/useUSDCPrice/index.ts
  src/custom/state/price/updater.ts
  src/custom/utils/price.ts
Labels: 🚀 RELEASE

#2023 change network name: xDai -> Gnosis Chain
  src/custom/assets/cow-swap/network-gnosis-chain-logo.svg
  src/custom/components/Header/index.tsx
  src/custom/constants/chains/chainsMod.ts
  src/custom/utils/xdai/constants.ts
Labels: app:CowSwap, Protofire, 🔥 Critical

#2010 Add new errors: InsufficientAllowance, InsufficientBalance
  src/custom/api/gnosisProtocol/errors/OperatorError.ts
Labels: Auto-merge

#2039 [2002 - return Fee data to UI] - Show fee amount when SellAmountDoesNotCoverFee
  src/custom/api/gnosisProtocol/errors/OperatorError.ts
  src/custom/api/gnosisProtocol/errors/QuoteError.ts
  src/custom/utils/price.ts
Labels: 🚀 RELEASE

#2040 [Release] 1.8.0-rc.1
  src/custom/api/gnosisProtocol/errors/OperatorError.ts
  src/custom/api/gnosisProtocol/errors/QuoteError.ts
  src/custom/hooks/usePriceImpact/useFallbackPriceImpact.ts
  src/custom/state/swap/utils.ts
  src/custom/utils/price.ts
Labels: 🚀 RELEASE

#1996 [Profile] Optimize API calls to IPFS service
  src/custom/components/AffiliateStatusCheck/index.tsx
  src/custom/state/affiliate/hooks.ts
Labels: Protofire
