Repository gnosis/cowswap, pull requests merged in 2021-11, with the labels that each got.

#1714 Affiliate issues
  src/custom/components/AffiliateStatusCheck/index.tsx
  src/custom/components/Header/index.tsx
  src/custom/components/NotificationBanner/index.tsx
  src/custom/hooks/useParseReferralQueryParam.ts
  src/custom/pages/Profile/index.tsx
  src/custom/pages/Profile/styled.tsx
  src/custom/state/affiliate/actions.ts
  src/custom/state/affiliate/hooks.ts
  src/custom/state/affiliate/reducer.ts
Labels: Protofire

#1743 Fix appDataHash initial state being undefined when state was rehydrated from local storage
  src/custom/state/affiliate/hooks.ts
  src/custom/state/affiliate/reducer.ts
Labels: Protofire

#1755 Add border radius to banner in Profile container
  src/custom/pages/Profile/index.tsx
Labels: Protofire

#1754 Fix Affiliate error banner showing up
  src/custom/components/AffiliateStatusCheck/index.tsx
  src/custom/state/affiliate/hooks.ts
  src/custom/state/affiliate/updater.tsx
Labels: Protofire

#1753 Add a loading indicator to Profile when loading data
  src/custom/hooks/useFetchProfile.ts
  src/custom/pages/Profile/index.tsx
Labels: Protofire

#1748 [Affiliate] Close all affiliate banners after a successful trade
  src/custom/components/AffiliateStatusCheck/index.tsx
  src/custom/components/Web3Status/index.tsx
  src/custom/state/affiliate/hooks.ts
Labels: 🐞 Bug, Protofire, Auto-merge

#1680 added auto-connect to latest wallet
  src/components/Web3ReactManager/index.tsx
  src/custom/hooks/useWalletInfo.ts
  src/custom/hooks/web3.ts
  src/hooks/web3.ts
Labels: 🚀 RELEASE

#1745 Adding errorState in useFetchProfile
  src/custom/hooks/useFetchProfile.ts
  src/custom/pages/Profile/index.tsx
Labels: Protofire

#1777 applied 50% width
  src/custom/pages/Profile/styled.tsx
Labels: Protofire, Auto-merge

#1789 Add meta-tags and improve social sharing
  .env
  README.md
  public/images/og-meta-cowswap.png
  public/index.html
Labels: 🚀 RELEASE

#1804 Remove unsupported list
  public/images/CowSwap-logo-256.png
  src/custom/constants/tokenLists/unsupported.tokenlist.json
Labels: 🚀 RELEASE

#1756 Feature/1730 notif banner miss adjusts
  src/custom/components/AffiliateStatusCheck/index.tsx
  src/custom/components/NotificationBanner/index.tsx
  src/custom/constants/index.ts
  src/custom/pages/Profile/index.tsx
  src/custom/state/affiliate/actions.ts
  src/custom/state/affiliate/hooks.ts
  src/custom/state/affiliate/reducer.ts
Labels: Protofire

#1703 [Affiliate] banner styles
  src/components/swap/styleds.tsx
  src/custom/components/Header/index.tsx
  src/custom/components/Menu/index.tsx
  src/custom/components/NotificationBanner/index.tsx
  src/custom/pages/App/AppMod.tsx
  src/custom/pages/Profile/index.tsx
  src/custom/pages/Profile/styled.tsx
  src/custom/pages/Swap/SwapMod.tsx
  src/custom/pages/Swap/index.tsx
Labels: app:CowSwap, Protofire

#1808 Add an id to the notification banner to track its closed status
  src/custom/components/AffiliateStatusCheck/index.tsx
  src/custom/components/Header/index.tsx
  src/custom/components/Menu/index.tsx
  src/custom/components/NotificationBanner/index.tsx
  src/custom/constants/index.ts
  src/custom/state/affiliate/actions.ts
  src/custom/state/affiliate/hooks.ts
  src/custom/state/affiliate/reducer.ts
Labels: 🚀 RELEASE, Protofire

#1691 [Affiliate] Add FAQ
  src/custom/components/AffiliateStatusCheck/index.tsx
  src/custom/pages/Faq/index.tsx
Labels: app:CowSwap, Protofire, Auto-merge

#1721 [Affiliate] Add tooltip and FAQ section
  src/custom/pages/Faq/index.tsx
  src/custom/pages/Profile/index.tsx
Labels: ☀️ Enhancement, app:CowSwap, Protofire

#1791 Do not update orders other accounts
  .eslintrc.json
  package.json
  src/custom/pages/Swap/SwapMod.tsx
  src/custom/state/orders/updaters/CancelledOrdersUpdater.ts
  src/custom/state/orders/updaters/PendingOrdersUpdater.ts
  src/custom/state/orders/updaters/UnfillableOrdersUpdater.ts
  src/service-worker.ts
  src/serviceWorkerRegistration.ts
Labels: 🚀 RELEASE

#1833 FAQ - Styles on Links
  package.json
  src/custom/pages/Faq/index.tsx
Labels: app:CowSwap, Protofire, Auto-merge

#1865 [Profile] Add name to IPFS files + Upload JSON using pinata
  package.json
  src/custom/api/ipfs/index.ts
  src/custom/utils/metadata.ts
  yarn.lock
Labels: 🐞 Bug, Protofire, 🔥 Critical

#1866 Hotfix 1.4.11
  package.json
  src/custom/api/ipfs/index.ts
  src/custom/utils/metadata.ts
  yarn.lock
Labels: 🚀 RELEASE

#1870 Fix e2e and autoconnect
  cypress-custom/integration/swap.test.ts
  src/custom/hooks/web3.ts
Labels: 🚀 RELEASE

#1824 add cases of the tooltip visibility
  src/custom/pages/Profile/index.tsx
Labels: Protofire, Auto-merge

#1826 adjusts for connect a wallet btn
  src/custom/components/Web3Status/index.tsx
  src/custom/pages/Profile/index.tsx
Labels: 🚀 RELEASE, app:CowSwap, Protofire, Auto-merge

#1886 Fix wrong label
  src/custom/components/AccountDetails/Transaction/StatusDetails.tsx
Labels: 🚀 RELEASE, Auto-merge

#1885 Always create a new state object when adding an order (#1686)
  src/custom/state/orders/reducer.ts
Labels: 🚀 RELEASE

#1894 (bugfix) Terms and conditions styles
  src/custom/pages/TermsAndConditions/TermsAndConditions.md
Labels: 🐞 Bug, app:CowSwap, Protofire, ❗️Medium, Auto-merge

#1889 Show proper warning when on barn
  src/custom/components/Header/URLWarning/index.tsx
  src/custom/constants/index.ts
Labels: Auto-merge

#1532 Handle cancel state for ethereum txs
  src/custom/hooks/useRecentActivity.ts
  src/custom/state/enhancedTransactions/actions.ts
  src/custom/state/enhancedTransactions/reducer.ts
  src/custom/state/enhancedTransactions/updater/CancelReplaceTxUpdater.tsx
Labels: Protofire

#1875 [Affiliate] Update banner closed state across tabs
  src/custom/components/NotificationBanner/index.tsx
  src/custom/state/affiliate/hooks.ts
  src/custom/state/affiliate/updater.tsx
Labels: Protofire

#1910 RC 1.5.0-rc.4
  package.json
  src/custom/components/AccountDetails/index.tsx
  src/custom/components/WalletModal/WalletModalMod.tsx
  src/custom/constants/index.ts
  src/custom/hooks/web3.ts
  yarn.lock
Labels: 🚀 RELEASE

#1911 Bumping version to 1.5
  package.json
Labels: 🚀 RELEASE

#1881 Filter emtpy queryParams
  src/custom/hooks/useFilterEmptyQueryParams.ts
  src/custom/pages/App/index.tsx
Labels: app:CowSwap, Protofire, Auto-merge

#1893 Update orders faster
  src/custom/state/orders/consts.ts
  src/custom/state/orders/updaters/CancelledOrdersUpdater.ts
  src/custom/state/orders/updaters/PendingOrdersUpdater.ts
  src/custom/state/orders/updaters/UnfillableOrdersUpdater.ts
Labels: 🚀 RELEASE

#1926 Change typo
  src/custom/pages/Faq/index.tsx
Labels: Auto-merge
