Repository gnosis/cowswap, pull requests merged in 2021-08, with the labels that each got.

#1161 Change tooltip
  src/custom/pages/Swap/index.tsx
Labels: RELEASE, merge when green

#1165 Balancer sc upgrade
  package.json
  src/custom/components/Version/index.tsx
  src/custom/constants/GPv2Settlement.json
  src/custom/constants/index.ts
  src/custom/hooks/useApproveCallback.ts
  src/custom/hooks/useERC20Permit/useERC20PermitMod.ts
  yarn.lock
Labels: DON'T MERGE

#1174 Renamed package name
  package.json
Labels: merge when green

#1180 Fix buy ETH
  src/custom/constants/index.ts
  src/custom/hooks/useSwapCallback.ts
Labels: High prio, RELEASE, merge when green

#1157 1017/fix managelist styles 2
  src/components/ListLogo/index.tsx
  src/custom/components/CurrencyInputPanel/index.tsx
  src/custom/components/SearchModal/ImportRow/index.tsx
  src/custom/components/SearchModal/ImportToken/index.tsx
  src/custom/components/SearchModal/ManageTokens/index.tsx
Labels: RELEASE

#1156 Make links to open in new page
  src/custom/components/Header/index.tsx
  src/custom/pages/About/index.tsx
  src/custom/pages/Faq/index.tsx
  src/custom/pages/TermsAndConditions/TermsAndConditions.md
Labels: RELEASE, merge when green

#1196 Update terms.
  src/custom/pages/TermsAndConditions/TermsAndConditions.md
Labels: RELEASE, merge when green

#1202 Add missing article
  src/custom/pages/Faq/index.tsx
Labels: RELEASE

#1200 Add dynamic announcements
  src/custom/components/Header/URLWarning/URLWarningMod.tsx
  src/custom/components/Header/URLWarning/index.tsx
  src/custom/hooks/useFetchFile.ts
  src/custom/state/index.ts
  src/custom/state/profile/actions.ts
  src/custom/state/profile/hooks.tsx
  src/custom/state/profile/reducer.ts
  src/custom/utils/misc.ts
Labels: RELEASE

#1212 Open links in new pages, refactor
  src/custom/components/ContentLink/index.tsx
  src/custom/components/Header/URLWarning/index.tsx
  src/custom/components/Link/index.tsx
  src/custom/components/Markdown/index.tsx
  src/custom/components/Markdown/renderers.tsx
  src/custom/components/MarkdownPage/index.tsx
  src/custom/pages/CookiePolicy/index.tsx
  src/custom/pages/Faq/index.tsx
  src/custom/pages/PrivacyPolicy/index.tsx
  src/custom/pages/TermsAndConditions/index.tsx
Labels: RELEASE

#1221 Update text & Link
  docs/announcements.md
Labels: RELEASE

#1201 162/use is order unfillable
  src/custom/components/AccountDetails/Transaction.tsx
  src/custom/constants/index.ts
  src/custom/state/orders/actions.ts
  src/custom/state/orders/consts.ts
  src/custom/state/orders/hooks.ts
  src/custom/state/orders/reducer.ts
  src/custom/state/orders/updater.ts
  src/custom/state/orders/updaters/CancelledOrdersUpdater.ts
  src/custom/state/orders/updaters/PendingOrdersUpdater.ts
  src/custom/state/orders/updaters/UnfillableOrdersUpdater.ts
  src/custom/state/orders/updaters/index.ts
  src/custom/state/orders/updaters/utils.ts
  src/index.tsx
Labels: Auto-merge

#1135 1120/consistent usd estimation and amounts display
  src/custom/components/CurrencyInputPanel/CurrencyInputPanelMod.tsx
  src/custom/components/swap/ConfirmSwapModal/ConfirmSwapModalMod.tsx
  src/custom/components/swap/ConfirmSwapModal/index.tsx
  src/custom/components/swap/FeeInformationTooltip.tsx
  src/custom/components/swap/SwapModalHeader/SwapModalHeaderMod.tsx
  src/custom/components/swap/TradePrice/TradePriceMod.tsx
  src/custom/components/swap/TradePrice/index.tsx
  src/custom/components/swap/TradeSummary/TradeSummaryMod.tsx
  src/custom/components/swap/TradeSummary/index.tsx
  src/custom/constants/index.ts
  src/custom/pages/Swap/index.tsx
  src/custom/utils/format.ts
Labels: Auto-merge

#1260 162/pr 1201 comments
  src/custom/state/orders/mocks.ts
  src/custom/state/orders/updaters/UnfillableOrdersUpdater.ts
  src/custom/state/orders/utils.test.ts
  src/custom/state/orders/utils.ts
Labels: Auto-merge

#1273 1267/Small price formatting issue
  src/custom/utils/format.ts
Labels: Auto-merge

#1282 1261/default slippage 1pct
  src/custom/constants/index.ts
  src/custom/pages/Swap/index.tsx
  src/custom/state/swap/hooks.ts
  src/custom/state/swap/trade.test.ts
Labels: Auto-merge

#1290 Add datatype for api additional data
  src/custom/components/AccountDetails/Transaction/index.tsx
  src/custom/state/orders/actions.ts
  src/custom/state/orders/mocks.ts
  src/custom/state/orders/utils.ts
  src/custom/utils/trade.ts
Labels: Auto-merge

#1307 Add docs and stats
  README.md
  src/custom/components/Menu/MenuMod.tsx
  src/custom/components/Menu/index.tsx
  src/custom/constants/index.ts
Labels: Auto-merge

#1355 Update question about MEV
  src/custom/pages/Faq/index.tsx
Labels: Auto-merge

#1314 [presign] Enable smart contracts
  src/custom/components/swap/ConfirmSwapModal/ConfirmSwapModalMod.tsx
  src/custom/components/swap/FeeInformationTooltip.tsx
  src/custom/components/swap/SwapModalHeader/SwapModalHeaderMod.tsx
  src/custom/components/swap/SwapModalHeader/index.tsx
  src/custom/components/swap/TradeSummary/RowReceivedAfterSlippage.tsx
  src/custom/components/swap/TradeSummary/index.tsx
  src/custom/hooks/useWalletInfo.ts
  src/custom/pages/Swap/SwapMod.tsx
  src/custom/pages/Swap/index.tsx
Labels: Auto-merge

#1315 999/2 decimals percentage
  package.json
  src/custom/components/CurrencyInputPanel/FiatValue/FiatValueMod.tsx
  src/custom/components/swap/TradeSummary/RowSlippage.tsx
  yarn.lock
Labels: Auto-merge

#1331 [Cowswap] Implement 404 error page
  src/custom/assets/cow-swap/cow-404.png
  src/custom/pages/App/index.tsx
  src/custom/pages/NotFound/index.tsx
Labels: Protofire, Auto-merge
