Repository gnosis/cowswap, pull requests merged in 2021-07, with the labels that each got.

#971 [877] Remove incompatible wallets
  src/constants/index.ts
  src/custom/components/WalletModal/WalletModalMod.tsx
  src/custom/constants/index.ts
  src/custom/hooks/useWalletInfo.ts
  src/custom/state/swap/trade.test.ts
Labels: RELEASE

#952 Add hook to generate the affiliate link
  src/assets/images/cows.png
  src/custom/components/Header/index.tsx
  src/custom/hooks/useReferralLink.ts
  src/custom/pages/App/index.tsx
  src/custom/pages/Rewards/index.tsx
Labels: protofire

#951 Add affiliate top link and affiliate base page
  src/custom/assets/cow-swap/cows-side-by-side.png
  src/custom/components/Header/index.tsx
  src/custom/pages/App/index.tsx
  src/custom/pages/Profile/index.tsx
Labels: DON'T MERGE, protofire

#968 [Affiliate] Copy link component
  src/custom/components/Copy/index.tsx
Labels: protofire

#990 Update mergify rules
  .mergify.yml
Labels: merge when green

#991 Adding pull request template
  .github/pull_request_template.md
Labels: merge when green

#982 Adds deterministicHash function to deterministically hash any value using sha256
  package.json
  src/custom/utils/deterministicHash.test.ts
  src/custom/utils/deterministicHash.ts
  yarn.lock
Labels: merge when green, protofire

#1024 Improve dark mode
  src/components/SearchModal/CurrencySearchModal.tsx
  src/custom/components/SearchModal/Manage/ManageMod.tsx
  src/custom/components/SearchModal/Manage/index.tsx
  src/custom/components/SearchModal/ManageLists/ManageListsMod.tsx
  src/custom/components/SearchModal/ManageLists/index.tsx
Labels: merge when green

#980 Add generateReferralMetadataDoc function
  src/custom/utils/metadata.ts
Labels: merge when green, protofire

#953 Adds useParseReferralQueryParam hook to parse the referral link from the url.
  src/custom/hooks/useParseReferralQueryParam.ts
  src/custom/pages/App/index.tsx
Labels: merge when green, protofire

#1037 [0.17] Fix trade.test.ts
  src/custom/state/swap/trade.test.ts
Labels: merge when green

#1031 Fix search token
  src/custom/components/CurrencyInputPanel/CurrencyInputPanelMod.tsx
  src/custom/components/CurrencyInputPanel/index.tsx
  src/custom/components/SearchModal/CurrencyList/CurrencyListMod.tsx
  src/custom/components/SearchModal/CurrencyList/index.tsx
Labels: merge when green

#1036 Fix mobile swap container
  src/custom/components/CurrencyInputPanel/CurrencyInputPanelMod.tsx
  src/custom/components/CurrencyInputPanel/index.tsx
  src/custom/components/swap/SwapModalHeader/SwapModalHeaderMod.tsx
  src/custom/pages/App/AppMod.tsx
  src/custom/pages/App/index.tsx
  src/custom/pages/Swap/SwapMod.tsx
  src/custom/pages/Swap/index.tsx
Labels: merge when green

#1038 Update wrong question about liquidity
  src/custom/pages/Faq/index.tsx
Labels: merge when green

#1033 [Release 🔥] 0.17.0-rc.1
  src/components/SearchModal/CurrencySearchModal.tsx
  src/custom/components/CurrencyInputPanel/CurrencyInputPanelMod.tsx
  src/custom/components/CurrencyInputPanel/index.tsx
  src/custom/components/SearchModal/CurrencyList/CurrencyListMod.tsx
  src/custom/components/SearchModal/CurrencyList/index.tsx
  src/custom/components/SearchModal/Manage/ManageMod.tsx
  src/custom/components/SearchModal/Manage/index.tsx
  src/custom/components/SearchModal/ManageLists/ManageListsMod.tsx
  src/custom/components/SearchModal/ManageLists/index.tsx
  src/custom/components/swap/SwapModalHeader/SwapModalHeaderMod.tsx
  src/custom/hooks/useERC20Permit/useERC20PermitMod.ts
  src/custom/pages/App/AppMod.tsx
  src/custom/pages/App/index.tsx
  src/custom/pages/Faq/index.tsx
  src/custom/pages/Swap/SwapMod.tsx
  src/custom/pages/Swap/index.tsx
  src/custom/state/swap/trade.test.ts
  src/hooks/useERC20Permit.ts
  src/hooks/useUSDCPrice.ts
Labels: RELEASE

#997 Add metadata document API request
  .env
  .env.production
  src/custom/utils/operator/errors/MetadataError.ts
  src/custom/utils/operator/index.ts
  src/custom/utils/operator/operatorApi.ts
  src/custom/utils/operator/operatorMock.ts
Labels: merge when green, protofire

#1001 [Affiliate] Notification banner component
  src/custom/components/NotificationBanner/index.tsx
  src/custom/theme/baseTheme.tsx
  src/custom/theme/styled.d.ts
Labels: merge when green, protofire

#1071 Reduce tooltip 🔥 🔥 HELL🔥 🔥
  src/custom/components/Settings/SettingsMod.tsx
  src/custom/components/Tooltip/TooltipMod.tsx
  src/custom/components/TransactionSettings/TransactionSettingsMod.tsx
  src/custom/components/swap/FeeInformationTooltip.tsx
  src/custom/components/swap/TradeSummary/TradeSummaryMod.tsx
  src/custom/pages/Swap/index.tsx
Labels: merge when green

#1074 Mobile responsive fixes for 1057
  src/custom/components/Modal/index.ts
  src/custom/components/TransactionConfirmationModal/TransactionConfirmationModalMod.tsx
  src/custom/components/TransactionConfirmationModal/index.tsx
  src/custom/components/WalletModal/WalletModalMod.tsx
  src/custom/components/swap/SwapModalHeader/index.tsx
Labels: merge when green

#1063 [1057] Fix mobile swap confirmation styling
  src/custom/components/AccountDetails/AccountDetailsMod.tsx
  src/custom/components/AccountDetails/Transaction.tsx
  src/custom/components/Modal/index.ts
  src/custom/components/TransactionConfirmationModal/TransactionConfirmationModalMod.tsx
  src/custom/components/TransactionConfirmationModal/index.tsx
  src/custom/components/WalletModal/WalletModalMod.tsx
  src/custom/components/WalletModal/index.tsx
  src/custom/components/swap/SwapModalHeader/index.tsx
Labels: merge when green

#1084 Fix / handle stale V2 order data type in V3
  src/custom/state/orders/hooks.ts
  src/custom/state/orders/reducer.ts
Labels: RELEASE, merge when green

#1082 Shadow/slider.
  src/custom/components/SearchModal/CommonBases/CommonBasesMod.tsx
  src/custom/components/SearchModal/CommonBases/index.ts
  src/custom/theme/baseTheme.tsx
  src/custom/theme/cowSwapTheme.tsx
  src/custom/theme/styled.d.ts
Labels: merge when green

#1086 [1070 waterfall] - Remove USD estimation from "Receive/From (incl. fee)"
  src/custom/components/swap/FeeInformationTooltip.tsx
Labels: RELEASE, merge when green

#1091 Fix issue with small prices
  src/custom/components/swap/TradePrice/index.tsx
  src/custom/constants/index.ts
Labels: merge when green

#1070 Price/Fee display UI change - Swap page and Confirmation Modal
  src/custom/components/swap/FeeInformationTooltip.tsx
  src/custom/components/swap/SwapModalHeader/SwapModalHeaderMod.tsx
  src/custom/components/swap/TradePrice/TradePriceMod.tsx
  src/custom/components/swap/TradePrice/index.tsx
  src/custom/components/swap/TradeSummary/TradeSummaryMod.tsx
  src/custom/constants/index.ts
  src/custom/pages/Swap/SwapMod.tsx
  src/custom/pages/Swap/index.tsx
  src/custom/utils/format.ts
Labels: RELEASE, merge when green

#1116 Container border styles fix
  src/custom/components/CurrencyInputPanel/index.tsx
  src/custom/components/swap/SwapModalHeader/index.tsx
Labels: merge when green

#1101 Update . at the end of FAQ Answers
  src/custom/pages/Faq/index.tsx
Labels: merge when green

#1127 1120/consistent usd estimation display
  src/custom/components/CurrencyInputPanel/FiatValue/FiatValueMod.tsx
  src/custom/components/swap/FeeInformationTooltip.tsx
  src/custom/components/swap/TradePrice/TradePriceMod.tsx
  src/custom/components/swap/TradePrice/index.tsx
  src/custom/constants/index.ts
  src/custom/pages/Swap/index.tsx
  src/custom/utils/format.ts
Labels: merge when green

#1121 Fix indent.
  src/custom/pages/Swap/index.tsx
Labels: merge when green

#1122 Fix xdai logos
  src/components/CurrencyInputPanel/index.tsx
  src/components/DoubleLogo/index.tsx
  src/components/PositionCard/V2.tsx
  src/components/PositionCard/index.tsx
  src/components/SearchModal/CommonBases.tsx
  src/components/SearchModal/CurrencyList.tsx
  src/components/swap/SwapModalHeader.tsx
  src/custom/components/CurrencyLogo/CurrencyLogoMod.tsx
  src/custom/components/CurrencyLogo/index.tsx
  src/custom/constants/tokens/index.ts
  src/pages/Swap/index.tsx
Labels: RELEASE

#1106 Add getAppDataDoc method
  .env
  .env.production
  package.json
  src/custom/utils/operator/errors/MetadataError.ts
  src/custom/utils/operator/index.ts
  src/custom/utils/operator/operatorApi.ts
  src/custom/utils/operator/operatorMock.ts
Labels: merge when green, protofire

#1025 Persist referral link
  src/custom/pages/App/AppMod.tsx
  src/custom/pages/App/index.tsx
  src/custom/state/affiliate/actions.ts
  src/custom/state/affiliate/reducer.ts
  src/custom/state/affiliate/updater.tsx
  src/custom/state/index.ts
Labels: merge when green, protofire
