Repository gnosis/cowswap, pull requests merged in 2021-09, with the labels that each got.

#1385 Hotfix 🔥 - 1.1.1 [removeChild Node crash]
  src/custom/utils/node.ts
  src/index.tsx
Labels: 🔥 Critical

#1302 Handle tx cancelation/speedup
  .env
  .env.production
  package.json
  src/custom/connectors/index.ts
  src/custom/pages/Swap/SwapMod.tsx
  src/custom/state/enhancedTransactions/actions.ts
  src/custom/state/enhancedTransactions/hooks.ts
  src/custom/state/enhancedTransactions/reducer.ts
  src/custom/state/enhancedTransactions/updater.tsx
  src/custom/state/index.ts
  src/custom/utils/blocknative.ts
  src/index.tsx
  yarn.lock
Labels: Protofire, Auto-merge

#1125 [Bugfix] Move About item from Header to ellipsis menu
  src/custom/components/Header/index.tsx
  src/custom/components/Menu/index.tsx
Labels: 🐞 Bug

#1371 added sentry-webpack plugin for source maps
  .env
  .env.production
  craco.config.js
  package.json
  yarn.lock
Labels: Auto-merge

#1189 Add appDataHash to state
  src/custom/state/affiliate/actions.ts
  src/custom/state/affiliate/reducer.ts
  src/custom/state/affiliate/updater.tsx
Labels: Protofire

#1295 Show WARNING on high fee relative to swap
  src/custom/components/HighFeeWarning/index.tsx
  src/custom/components/swap/SwapModalHeader/SwapModalHeaderMod.tsx
  src/custom/components/swap/SwapModalHeader/index.tsx
  src/custom/components/swap/TradeSummary/RowFee.tsx
  src/custom/components/swap/TradeSummary/RowReceivedAfterSlippage.tsx
  src/custom/components/swap/TradeSummary/RowSlippage.tsx
  src/custom/constants/index.ts
  src/custom/pages/Swap/SwapMod.tsx
  src/custom/pages/Swap/index.tsx
  src/custom/pages/Swap/styleds.tsx
  src/custom/state/swap/hooks.ts
  src/custom/theme/baseTheme.tsx
  yarn.lock
Labels: Auto-merge

#1419 Hotfix :fire: - 1.1.3 [revert default slippage to 0.5%]
  src/custom/constants/index.ts
Labels: ⛔️ DON'T MERGE

#1423 High Fee Warning: fix colour/bgColour
  src/custom/components/HighFeeWarning/index.tsx
  src/custom/components/swap/SwapModalHeader/index.tsx
Labels: 🚀 RELEASE, Auto-merge

#1424 Fix: rename weth9 to weth (#2133) (UNI cherry-pick)
  package.json
  yarn.lock
Labels: 🚀 RELEASE

#1416 [presign] Fix pending loader not showing up
  src/custom/components/Web3Status/index.tsx
Labels: Auto-merge

#1190 Update Metadata type
  src/custom/api/gnosisProtocol/mock.ts
  src/custom/utils/metadata.ts
Labels: Protofire, Auto-merge

#1443 Fix cypress
  cypress-custom/integration/swap.test.ts
  yarn.lock
Labels: Auto-merge

#1434 Bugfix - Copy to clipboard button not working on Wallet connect popup
  package.json
  yarn.lock
Labels: 🐞 Bug, Protofire

#1449 Display `0` when there's no balance to format
  src/custom/components/CurrencyInputPanel/CurrencyInputPanelMod.tsx
  src/custom/components/SearchModal/CurrencyList/index.tsx
Labels: Auto-merge

#1455 [release/1.2] change profile to about link
  src/custom/components/Header/index.tsx
  src/custom/components/Menu/index.tsx
Labels: 🚀 RELEASE

#1448 1441/input copy paste error
  src/custom/utils/format.ts
  src/state/swap/hooks.ts
Labels: 🚀 RELEASE, Auto-merge

#1456 [1436] Divide by zero fix
  src/custom/api/gnosisProtocol/errors/QuoteError.ts
  src/custom/hooks/useRefetchPriceCallback.tsx
  src/custom/pages/Swap/SwapMod.tsx
  src/custom/state/price/actions.ts
Labels: 🚀 RELEASE

#1471 Make terms and conditions text bold
  src/custom/pages/Faq/index.tsx
Labels: Auto-merge

#1472 Truncating error msg when opening GH issue via URL
  src/custom/components/ErrorBoundary/ErrorBoundaryMod.tsx
Labels: Auto-merge

#1393 [Profile] Upload metada doc to IPFS
  package.json
  src/custom/api/ipfs/index.ts
  src/custom/constants/ipfs.ts
  src/custom/utils/metadata.ts
  yarn.lock
Labels: Protofire, Auto-merge

#1476 Added linter step with auto-fix
  .eslintrc.json
  .github/workflows/ci.yml
  .mergify.yml
  .prettierignore
  CONTRIBUTING.md
  README-uni.md
  README.md
  cypress.json
  public/manifest.json
  src/assets/metadata/CowSwap-ENS.json
  src/assets/metadata/CowSwap-barn.json
  src/assets/metadata/CowSwap-development.json
  src/assets/metadata/CowSwap-local.json
  src/assets/metadata/CowSwap-pr.json
  src/assets/metadata/CowSwap-production.json
  src/assets/metadata/CowSwap-staging.json
  src/assets/metadata/ipfs_hashes.json
  src/custom/constants/GPv2Settlement.json
  src/custom/pages/CookiePolicy/CookiePolicy.md
  src/custom/pages/TermsAndConditions/TermsAndConditions.md
  src/locales/README.md
  tsconfig.json
Labels: Auto-merge

#1482 Feature/1480 inline copy btn
  src/custom/pages/Profile/index.tsx
Labels: Protofire

#1492 Only use default precision on formatMax when decimals is null|undefined
  src/custom/utils/format.ts
Labels: 🔥 Critical

#1497 Hotfix/1.2.1
  package.json
  src/custom/utils/format.ts
Labels: 🚀 RELEASE
