Repository gnosis/cowswap, pull requests merged in 2021-10, with the labels that each got.

#1433 [Paraswap] migration to v5
  package.json
  src/custom/api/paraswap/index.ts
  src/custom/constants/index.ts
  src/custom/hooks/useUSDCPrice/index.ts
  src/custom/state/price/updater.ts
  src/custom/utils/price.ts
  yarn.lock
Labels: Auto-merge

#1514 icons & titles used correctly
  package.json
  src/custom/api/gnosisProtocol/api.ts
  src/custom/api/gnosisProtocol/index.ts
  src/custom/api/gnosisProtocol/mock.ts
  src/custom/components/Header/index.tsx
  src/custom/hooks/useFetchProfile.ts
  src/custom/hooks/useReferralLink.ts
  src/custom/hooks/useTimeAgo.ts
  src/custom/pages/Profile/index.tsx
  src/custom/utils/format.ts
  yarn.lock
Labels: Protofire, Auto-merge

#1630 [CI.yml] ignore "locale" cache in lint step
  .github/workflows/ci.yml
Labels: Auto-merge

#1644 [closes #1634] - Cannot click polling block
  src/custom/pages/App/AppMod.tsx
Labels: 🚀 RELEASE

#1645 [closes #1600] - Fix expert mode toggle switch
  src/custom/components/Toggle/index.tsx
  src/custom/theme/baseTheme.tsx
Labels: 🚀 RELEASE

#1648 [RELEASE] 1.3.0
  src/custom/assets/cow-swap/network-mainnet-logo.svg
  src/custom/assets/cow-swap/network-rinkeby-logo.svg
  src/custom/assets/cow-swap/network-xdai-logo.svg
  src/custom/components/ErrorBoundary/ErrorBoundaryMod.tsx
  src/custom/components/Header/NetworkCard/NetworkCardMod.tsx
  src/custom/components/Header/index.tsx
  src/custom/components/Toggle/index.tsx
  src/custom/constants/chains/chainsMod.ts
  src/custom/pages/App/AppMod.tsx
  src/custom/theme/baseTheme.tsx
  src/custom/theme/cowSwapAssets.ts
  src/custom/theme/cowSwapTheme.tsx
  src/custom/theme/styled.d.ts
Labels: 🚀 RELEASE

#1666 [HOTFIX] 1.3.1
  package.json
  yarn.lock
Labels: 🚀 RELEASE
