Repository gnosis/cowswap, pull requests merged in 2022-02, with the labels that each got.

#2399 Menu: view all orders position
  src/custom/components/AccountDetails/index.tsx
  src/custom/components/Menu/index.tsx
Labels: ☀️ Enhancement, app:CowSwap, Protofire, Auto-merge

#2403 gip-13 data - Update contract
  src/custom/constants/index.ts
  src/custom/state/claim/hooks/index.ts
Labels: 🚀 RELEASE

#2353 Enable Coinbase Wallet (wallet-link)
  package.json
  src/custom/connectors/index.ts
  src/custom/constants/index.ts
  src/custom/hooks/web3.ts
  src/react-app-env.d.ts
  yarn.lock
Labels: app:CowSwap, Protofire

#2422 Set up Fortmatic wallet environment
  .env.production
  src/custom/connectors/Fortmatic.ts
  src/custom/connectors/index.ts
Labels: app:CowSwap, Protofire

#2430 [HOTFIX 🔥 🔥 🔥 ] - v1.10.2
  src/custom/constants/chains/chainsMod.ts
  src/custom/pages/Claim/ClaimsOnOtherChainsBanner.tsx
  src/custom/pages/Claim/InvestmentFlow/InvestOption.tsx
  src/custom/pages/Claim/InvestmentFlow/index.tsx
  src/custom/state/claim/hooks/index.ts
  src/custom/state/claim/hooks/utils.ts
  src/custom/state/claim/reducer.ts
  src/custom/utils/addNetwork.ts
  src/custom/utils/switchToNetwork.ts
Labels: 🚀 RELEASE

#2414 Enhance messages for Affiliate program
  src/custom/components/AffiliateStatusCheck/index.tsx
Labels: ☀️ Enhancement, Protofire, ❗️Medium, Auto-merge

#2421 Scrollbar styles
  src/custom/components/SearchModal/CommonBases/index.ts
  src/custom/components/SearchModal/CurrencyList/CurrencyListMod.tsx
  src/custom/components/SearchModal/ManageLists/ManageListsMod.tsx
  src/custom/components/TransactionConfirmationModal/TransactionConfirmationModalMod.tsx
  src/custom/theme/baseTheme.tsx
  src/custom/theme/styled.d.ts
Labels: 🐞 Bug, app:CowSwap, ⬇ Low, Protofire, Auto-merge

#2483 2150 Terms and Conditions: gnosis forum link
  src/custom/pages/TermsAndConditions/TermsAndConditions.md
Labels: 🐞 Bug, app:CowSwap, ⬇ Low, Protofire, Auto-merge

#2491 [HOTFIX] 1.10.3
  src/custom/api/gnosisProtocol/api.ts
  src/custom/utils/tokens.ts
Labels: 🚀 RELEASE

#2488 Swap page layout
  src/custom/components/Footer/index.tsx
  src/custom/pages/App/index.tsx
Labels: 🐞 Bug, app:CowSwap, Protofire, Auto-merge
