Repository gnosis/cowswap, pull requests merged in 2022-01, with the labels that each got.

#2047 [Rebranding] Update Explorer FE and BE api URLs
  .env.production
  src/custom/api/gnosisProtocol/api.ts
Labels: Protofire, 🔥 Critical

#2058 Hotfix 1.8.1 - Rebranding
  .env.production
  README.md
  package.json
  public/index.html
  src/custom/api/gnosisProtocol/api.ts
  src/custom/constants/index.ts
  src/custom/pages/About/index.tsx
  src/custom/pages/App/index.tsx
  src/custom/pages/Faq/index.tsx
Labels: 🚀 RELEASE

#2051 [Claim] Profile: vCOW balance
  src/custom/components/Page/index.tsx
  src/custom/pages/Profile/index.tsx
  src/custom/pages/Profile/styled.tsx
Labels: app:CowSwap, Protofire, Auto-merge

#2071 [1.8.1] Update BARN urls
  .env.production
  cypress-custom/integration/fee.test.ts
  src/custom/api/gnosisProtocol/api.ts
  src/custom/utils/explorer.ts
Labels: 🐞 Bug, 🔥 Critical

#2073 Update gnosis chain logo
  src/custom/assets/cow-swap/network-gnosis-chain-logo.svg
Labels: ☀️ Enhancement, app:CowSwap, Protofire, 🔥 Critical, Auto-merge

#2078 [1.8.1] Update BARN url for /profile request
  src/custom/api/gnosisProtocol/api.ts
Labels: 🐞 Bug, 🔥 Critical

#2086 Update contract to new deployment
  src/custom/constants/index.ts
Labels: Auto-merge

#2062 vCOW on profile
  src/custom/pages/Profile/index.tsx
Labels: Auto-merge

#2122 Update xdai and wxdai token logo
  src/assets/images/wxdai.png
  src/assets/images/xdai.png
  src/custom/components/CurrencyLogo/CurrencyLogoMod.tsx
  src/custom/constants/tokens/index.ts
Labels: 🐞 Bug, app:CowSwap, Protofire, ❗️Medium, Auto-merge

#2140 Replace Gnosis Protocol --> CoW Protocol
  .github/workflows/ci.yml
  README.md
  package.json
  public_uniswap/index.html
  src/custom/api/gnosisProtocol/api.ts
  src/custom/components/SearchModal/CurrencyList/index.tsx
  src/custom/components/swap/UnsupportedCurrencyFooter/index.tsx
  src/custom/pages/TermsAndConditions/TermsAndConditions.md
Labels: 🐞 Bug, app:CowSwap, Protofire, ❗️Medium, Auto-merge

#2060 new progressbar component of claim branch && more values available
  src/custom/components/ProgressBar/index.tsx
  src/custom/components/ProgressBar/styled.tsx
  src/custom/pages/Profile/index.tsx
Labels: app:CowSwap, Protofire, Auto-merge

#2123 Fix native investment
  src/custom/state/claim/hooks/index.ts
Labels: Auto-merge

#2177 Remove progress bar from Profile page
  src/custom/pages/Profile/index.tsx
Labels: app:CowSwap, Protofire

#2237 Total vcow on investment summary
  src/custom/pages/Claim/ClaimSummary.tsx
  src/custom/pages/Claim/InvestmentFlow/index.tsx
  src/custom/pages/Claim/index.tsx
Labels: Auto-merge

#2241 Disable claim review on errors
  src/custom/pages/Claim/FooterNavButtons.tsx
  src/custom/pages/Claim/InvestmentFlow/InvestOption.tsx
  src/custom/state/claim/actions.ts
  src/custom/state/claim/hooks/index.ts
  src/custom/state/claim/reducer.ts
Labels: Auto-merge

#2254 Claim invest general error msg
  src/custom/pages/Claim/FooterNavButtons.tsx
  src/custom/pages/Claim/InvestmentFlow/index.tsx
  src/custom/state/claim/hooks/index.ts
Labels: Auto-merge

#2013 switcher added
  src/custom/components/Settings/SettingsMod.tsx
  src/custom/components/Toggle/index.tsx
  src/custom/components/swap/SwapModalHeader/SwapModalHeaderMod.tsx
  src/custom/pages/Swap/SwapMod.tsx
  src/state/user/actions.ts
  src/state/user/hooks.tsx
  src/state/user/reducer.ts
Labels: app:CowSwap, Protofire

#2256 Warning claim too much eth
  src/custom/components/swap/EthWethWrap/helpers.ts
  src/custom/components/swap/EthWethWrap/index.tsx
  src/custom/constants/index.ts
  src/custom/pages/Claim/InvestmentFlow/InvestOption.tsx
  src/custom/pages/Claim/styled.ts
Labels: Auto-merge

#2301 Fix claim table price
  src/custom/pages/Claim/ClaimsTable.tsx
Labels: Auto-merge

#2316 Claim balance on vcow button
  src/custom/components/CowClaimButton/index.tsx
  src/custom/components/Header/index.tsx
  src/custom/components/Menu/index.tsx
  src/custom/pages/Profile/VCOWDropdown.tsx
Labels: Auto-merge

#2329 Move affiliate banner to the top in Profile page
  src/custom/pages/Profile/index.tsx
Labels: Protofire

#1829 blur bg on err pages
  src/custom/components/ErrorBoundary/ErrorBoundaryMod.tsx
  src/custom/components/Header/index.tsx
Labels: app:CowSwap, Protofire

#2308 [RELEASE ⛰️ ] v1.10.0-RC.1
  src/components/claim/ClaimModal.tsx
  src/custom/assets/cow-swap/cowprotocol.svg
  src/custom/assets/cow-swap/important.svg
  src/custom/assets/cow-swap/round-arrow.svg
  src/custom/components/CowClaimButton/index.tsx
  src/custom/components/CowProtocolLogo/index.tsx
  src/custom/components/EnhancedTransactionLink/index.tsx
  src/custom/components/FaqDrawer/index.tsx
  src/custom/components/Header/NetworkSelector/NetworkSelectorMod.tsx
  src/custom/components/Header/index.tsx
  src/custom/components/Menu/index.tsx
  src/custom/components/NotificationBanner/index.tsx
  src/custom/components/ProgressBar/index.tsx
  src/custom/components/ProgressBar/styled.tsx
  src/custom/components/Stepper/index.tsx
  src/custom/constants/index.ts
  src/custom/hooks/useChangeNetworks.ts
  src/custom/pages/Claim/CanUserClaimMessage.tsx
  src/custom/pages/Claim/ClaimNav.tsx
  src/custom/pages/Claim/ClaimingStatus.tsx
  src/custom/pages/Claim/ClaimsOnOtherChainsBanner.tsx
  src/custom/pages/Claim/ClaimsTable.tsx
  src/custom/pages/Claim/EligibleBanner.tsx
  src/custom/pages/Claim/FooterNavButtons.tsx
  src/custom/pages/Claim/InvestmentFlow/InvestOption.tsx
  src/custom/pages/Claim/InvestmentFlow/InvestSummaryRow.tsx
  src/custom/pages/Claim/InvestmentFlow/index.tsx
  src/custom/pages/Claim/const.ts
  src/custom/pages/Claim/index.tsx
  src/custom/pages/Claim/styled.ts
  src/custom/pages/Profile/VCOWDropdown.tsx
  src/custom/state/claim/actions.ts
  src/custom/state/claim/hooks/index.ts
  src/custom/state/claim/hooks/mocks/claimData.ts
  src/custom/state/claim/reducer.ts
  src/custom/state/claim/updater.tsx
  src/custom/state/orders/utils.ts
  src/custom/theme/baseTheme.tsx
  src/custom/theme/styled.d.ts
  src/custom/utils/index.ts
  src/index.tsx
Labels: 🚀 RELEASE
