Repository gnosis/cowswap, pull requests merged in 2022-03, with the labels that each got.

#2166 Use previously supported wallets
  .env
  .env.production
  package.json
  src/constants/wallet.ts
  src/custom/components/WalletModal/WalletModalMod.tsx
  src/custom/components/Web3Status/Web3StatusMod.tsx
  src/custom/components/Web3Status/index.tsx
  src/custom/connectors/Fortmatic.ts
  src/custom/connectors/index.ts
  src/custom/constants/index.ts
  src/custom/hooks/web3.ts
  src/react-app-env.d.ts
  yarn.lock
Labels: app:CowSwap, Protofire

#2474 Fix race condition when replacing/cancelling on-chain txs
  src/custom/state/enhancedTransactions/reducer.ts
  src/custom/state/enhancedTransactions/updater/CancelReplaceTxUpdater.tsx
Labels: Protofire

#2521 Swap container on large screens
  src/custom/pages/App/index.tsx
  src/custom/theme/styled.d.ts
  src/theme/index.tsx
Labels: 🐞 Bug, app:CowSwap, Protofire, ❗️Medium, Auto-merge

#2523 Layout improvements
  src/custom/components/Footer/index.tsx
  src/custom/pages/App/index.tsx
Labels: app:CowSwap, Protofire, ❗️Medium, Auto-merge

#2525 [HOTFIX 🔥 ] 1.11.1
  src/custom/api/gnosisProtocol/api.ts
  src/custom/utils/logging/index.ts
Labels: 🚀 RELEASE

#2528 Confirmation modal - Cow runner game
  src/custom/assets/cow-swap/cows-side-by-side.png
  src/custom/components/TransactionConfirmationModal/index.tsx
Labels: 🐞 Bug, app:CowSwap, ⬇ Low, Protofire, Auto-merge

#2526 Add waiting time to reconnection
  src/constants/wallet.ts
  src/custom/constants/index.ts
  src/custom/hooks/web3.ts
Labels: app:CowSwap, Protofire

#2495 Gnosis safe app
  craco.config.js
  package.json
  public/manifest.json
  src/custom/connectors/index.ts
  src/custom/hooks/useWalletInfo.ts
  src/custom/hooks/web3.ts
  src/custom/theme/baseTheme.tsx
Labels: Auto-merge

#2542 [🔥 🔥 Hotfix] 1.11.2 - Unfillable Orders quote issue
  src/constants/wallet.ts
  src/custom/constants/index.ts
  src/custom/hooks/useSwapCallback.ts
  src/custom/hooks/web3.ts
  src/custom/state/orders/actions.ts
  src/custom/state/orders/mocks.ts
  src/custom/state/orders/updaters/GpOrdersUpdater.ts
  src/custom/state/orders/updaters/UnfillableOrdersUpdater.ts
  src/custom/utils/trade.ts
Labels: 🚀 RELEASE

#2556 Change warning on the profile page
  src/custom/hooks/useFetchListCallback/useFetchListCallbackMod.ts
  src/custom/pages/Profile/index.tsx
Labels: 🐞 Bug, app:CowSwap, Protofire, ❗️Medium, Auto-merge

#2572 Styling of vesting breakdown tooltip
  src/custom/assets/cow-swap/arrow.svg
  src/custom/assets/cow-swap/cow_v2.svg
  src/custom/assets/cow-swap/question.ts
  src/custom/assets/cow-swap/vCOW.png
  src/custom/components/Page/index.tsx
  src/custom/pages/Profile/index.tsx
  src/custom/pages/Profile/styled.tsx
Labels: 🚀 RELEASE

#2576 Added swapAll abi
  src/custom/abis/types/VCow.d.ts
  src/custom/abis/types/factories/VCow__factory.ts
  src/custom/abis/vCow.json
Labels: 🚀 RELEASE

#2575 Styled governance banner and inner card container.
  src/custom/pages/Claim/styled.ts
  src/custom/pages/Profile/styled.tsx
  src/custom/theme/baseTheme.tsx
  src/custom/theme/styled.d.ts
Labels: 🚀 RELEASE

#2568 Show real vCow and Cow data on profile page
  src/custom/abis/types/VCow.d.ts
  src/custom/abis/types/factories/VCow__factory.ts
  src/custom/abis/vCow.json
  src/custom/constants/index.ts
  src/custom/pages/Profile/index.tsx
  src/custom/pages/Profile/styled.tsx
  src/custom/state/claim/hooks/index.ts
Labels: 🚀 RELEASE

#2574 [CoW Subsidy] - connect real hook to other stuff
  src/custom/components/CowSubsidyModal/index.tsx
  src/custom/hooks/useCowBalanceAndSubsidy.ts
Labels: 🚀 RELEASE

#2577 Added swap vCow for Cow hook
  src/custom/components/TransactionConfirmationModal/index.tsx
  src/custom/pages/Profile/index.tsx
  src/custom/state/claim/actions.ts
  src/custom/state/claim/hooks/index.ts
  src/custom/state/claim/middleware.ts
  src/custom/state/claim/reducer.ts
  src/custom/state/enhancedTransactions/actions.ts
  src/custom/state/enhancedTransactions/hooks/index.ts
  src/custom/state/enhancedTransactions/reducer.ts
Labels: 🚀 RELEASE

#2567 [Logging] - Only hide logs in production and ens environments
  src/polyfills.ts
Labels: 🚀 RELEASE

#2590 [Subsidy] - Show fee breakdown adjusted for subsidy!
  src/custom/components/swap/FeeInformationTooltip.tsx
  src/custom/components/swap/SwapModalHeader/SwapModalHeaderMod.tsx
  src/custom/pages/Swap/SwapMod.tsx
Labels: 🚀 RELEASE

#2609 [Hotfix] 1.12.4
  craco.config.js
  src/custom/constants/tokens/index.ts
  src/custom/state/price/updater.ts
Labels: 🚀 RELEASE
